apiVersion: v1
kind: Service
metadata:
  name: proxy-api
  labels:
    {{- $_ := merge (dict "componentSuffix" "-api") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
spec:
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
