# A service for the mlflow api
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mlflow.fullname" . }}-headless
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "splice.subchart" . }}
    release: {{ .Release.Name }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
spec:
  ports:
  - port: {{ $.Values.mlflow.port.dash }}
    name: job-tracker
  - port: {{ $.Values.mlflow.port.mlflow }}
    name: mlflow
  clusterIP: None
  selector:
    app: {{ template "mlflow.name" . }}
    release: {{ .Release.Name }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
