apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "mlflow.fullname" . }}
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "splice.subchart" . }}
    release: {{ .Release.Name }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
spec:
  selector:
    matchLabels:
      app: {{ include "mlflow.name" . }}
      release: {{ .Release.Name }}
      dnsprefix: {{ .Values.global.dnsPrefix }}
  serviceName: {{ include "mlflow.fullname" . }}-headless
  replicas: {{ .Values.mlflow.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "mlflow.name" . }}
        release: {{ .Release.Name }}
        dnsprefix: {{ .Values.global.dnsPrefix }}
    spec:
      {{- if .Values.global.nodeSelector.enabled }}
      nodeSelector:
        components: {{ .Values.global.nodeSelector.meta }}
      {{- end }}
      initContainers:
      - name: check-db-ready
        image: {{ template "base-image" . }}
        command:
          - "sh"
          - "-c"
          - "until /usr/bin/curl -kLs -X GET http://{{ template "hbase.hregion.fullname" . }}-hl:16030/jmx?qry=com.splicemachine.version:type=DatabaseVersion | grep -q Release; do echo waiting for database; sleep 2; done;"
      containers:
      - name: mlflow
        image: {{ template "mlflow.image" . }}
        imagePullPolicy: {{ .Values.mlflow.image.pullPolicy }}
        env:
          - name: DB_HOST
            value: {{ template "splice.fullname" . }}-hregion.{{ template "svc-domain" . }}
          - name: DB_USER
            value: {{ .Values.global.mlmanager.user }}
          - name: DB_PASSWORD
            value: {{ .Values.global.mlmanager.password }}
          - name: FRAMEWORK_NAME
            value: {{ include "frameworkId" . }}
          - name: MODE
            value: {{ .Values.mlflow.image.mode }}
          - name: BOBBY_URL
            value: http://{{ include "bobby.fullname" . }}-headless
          - name: ENVIRONMENT
            value: {{ .Values.global.cloudprovider }}
          - name: TZ
            value: {{ .Values.global.timezoneFlag }}
        command:
        - "/bin/bash"
        - "/opt/mlflow/scripts/entrypoint.sh"
        resources:
{{ toYaml .Values.mlflow.resources | indent 10 }}


