{{- if eq .Values.global.cloudprovider "aws" }}
apiVersion: v1
kind: ServiceAccount
metadata:
   name: sagemaker
   namespace: {{ .Release.Namespace }}
   annotations:
      eks.amazonaws.com/role-arn: {{ .Values.mlflow.sageMakerRole }}
{{- end}}
