# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.datanode.fullname" . }}
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: {{ include "hdfs.datanode.component" . }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
spec:
  ports:
  - name: dfs
    port: 9000
    protocol: TCP
  - name: webhdfs
    port: 50075
  clusterIP: None
  selector:
    app: {{ include "hadoop.name" . }}
    release: {{ .Release.Name }}
    component: {{ include "hdfs.datanode.component" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}


