# A service for the mlflow user interface
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mlflow.fullname" . }}
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "splice.subchart" . }}
    release: {{ .Release.Name }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
spec:
  type: ClusterIP
  ports:
  - port: {{ $.Values.mlflow.port.mlflow }}
    name: mlflow
  - port: {{ $.Values.mlflow.port.dash }}
    name: job-tracker
  selector:
    app: {{ template "mlflow.name" . }}
    release: {{ .Release.Name }}
    dnsprefix: {{ .Values.global.dnsPrefix }}