apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: {{ .Release.Name -}}-olap
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - splicedbcluster.splicemachine.io
  resources:
  - '*'
  verbs:
  - '*'
