{{- if .Values.global.tls.enabled }}
apiVersion: v1
data:
  tls.crt: {{ .Values.global.tls.crt | b64enc }}
  tls.key: {{ .Values.global.tls.key | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.global.certificateName }}
type: kubernetes.io/tls
{{- end -}}
