apiVersion: v1
entries:
  splice-helm:
  - apiVersion: v1
    appVersion: "3.0"
    created: "2020-07-08T00:43:36.979884354Z"
    description: A Helm chart for launching Splice Machine on Kubernetes
    digest: b705369d24f6341ca672905314f504334101cff843e495c214644afc55b6d58d
    home: https://www.splicemachine.com
    icon: https://splicemachine.github.io/sm.logo.800x200px_180509.svg
    maintainers:
    - email: cloud-support@splicemachine.com
      name: cloud-support
    name: splice-helm
    urls:
    - splice-helm-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: "3"
    created: "2020-07-08T00:43:36.972245946Z"
    description: A Helm chart for launching Splice Machine on Kubernetes
    digest: 5808b2b21219c5090830997133228e394d2bb755b60a896abbbff37e424ec719
    home: https://www.splicemachine.com
    icon: https://splicemachine.github.io/sm.logo.800x200px_180509.svg
    maintainers:
    - email: cloud-support@splicemachine.com
      name: cloud-support
    name: splice-helm
    urls:
    - splice-helm-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-08T00:43:36.965493784Z"
    description: A Helm chart for launching Splice Machine on Kubernetes
    digest: f4759d3d4d544e44a11afd4ed4226d94ed437438f9405e09817b6bef1c6f9b0f
    home: https://www.splicemachine.com
    icon: https://splicemachine.github.io/sm.logo.800x200px_180509.svg
    maintainers:
    - email: cloud-support@splicemachine.com
      name: cloud-support
    name: splice-helm
    urls:
    - splice-helm-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-08T00:43:36.957077711Z"
    description: A Helm chart for launching Splice Machine on Kubernetes
    digest: 2fa1f0d7c59bb6098b4184819330c2525c9284f75ee12964f417182b56bbf8ae
    home: https://www.splicemachine.com
    icon: https://splicemachine.github.io/sm.logo.800x200px_180509.svg
    maintainers:
    - email: cloud-support@splicemachine.com
      name: cloud-support
    name: splice-helm
    urls:
    - splice-helm-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-07-08T00:43:36.9500193Z"
    description: A Helm chart for launching Splice Machine on Kubernetes
    digest: ba748abda665462e17f91c92f5249d3eec9d60e169704fc2e95a0d9575cdac80
    home: https://www.splicemachine.com
    icon: https://splicemachine.github.io/sm.logo.800x200px_180509.svg
    maintainers:
    - email: cloud-support@splicemachine.com
      name: cloud-support
    name: splice-helm
    urls:
    - splice-helm-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-08T00:43:36.9415597Z"
