controller:
  name: controller
  image:
    repository: splicemachine/kubernetes-ingress
    tag: 2.0.11_0.0.1
    pullPolicy: IfNotPresent
  replicaCount: 1
  config:
    syslog-server: "address:stdout, format: raw, facility:daemon, level: info"
    timeout-tunnel: "23h"
  # The secret will be looked for in the namespace the controller is installed into.
  defaultTLSSecret:
    enabled: true
    secret: REPLACE_CERTIFICATE

global:
  nodeSelector:
    enabled: true
    db: db
    core: core
    meta: meta
