apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: haproxy-ingress
    component: controller
    release: {{ .Release.Name }}
  name: {{ template "kubernetes-ingress.fullname" . }}
data:
{{- if .Values.controller.config }}
{{ toYaml .Values.controller.config | indent 2 }}
{{- end }}