apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "240"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- if .Values.global.haproxyPrivate }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    {{- end }}
  labels:
    app: haproxy-ingress
    component: controller
    release: {{ .Release.Name }}
    run: {{ template "kubernetes-ingress.fullname" . }}
  name: {{ template "kubernetes-ingress.fullname" . }}
spec:
  selector:
    run: {{ template "kubernetes-ingress.fullname" . }}
  type: LoadBalancer
  ports:
  - name: jdbc
    port: 1527
    protocol: TCP
    targetPort: 1527
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
