kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: haproxy-ingress
    component: controller
    release: {{ .Release.Name }}
  name: {{ template "kubernetes-ingress.fullname" . }}-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubernetes-ingress.fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubernetes-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
