apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: haproxy-ingress
    component: controller
    release: {{ .Release.Name }}
  name: {{ template "kubernetes-ingress.fullname" . }}-tcp
data:
  1527:
    {{ .Release.Namespace }}/{{ template "hbase.hregion.fullname" . }}:1527
  9092:
    {{ .Release.Namespace }}/{{ template "kafka.fullname" . }}:9092