kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splicedb-operator
subjects:
- kind: ServiceAccount
  name: splicedb-operator
  namespace: splice-system
roleRef:
  kind: Role
  name: splicedb-operator
  apiGroup: rbac.authorization.k8s.io
