{{- if .Values.external.enabled }}
  {{- $fullName := include  "kafka.fullname" . }}
  {{- $kafkaName := include  "kafka.name" . }}
  {{- $kafkaChart := include  "kafka.chart" . }}
  {{- $kafkaComponent := include  "kafka.component" . }}
  {{- $frameworkId := include  "frameworkId" . }}

  {{- $replicas := .Values.replicas | int }}
  {{- $servicePort := .Values.external.servicePort }}
  {{- $firstListenerPort := .Values.external.firstListenerPort }}
  {{- $dnsPrefix := .Values.global.dnsPrefix }}

  {{- $root := . }}
  {{- range $i, $e := until $replicas }}
    {{- $externalListenerPort := add $root.Values.external.firstListenerPort $i }}
    {{- $responsiblePod := printf "%s-%d" (printf "%s" $fullName) $i }}
    {{- $distinctPrefix := printf "kafka-%d" $i }}
    {{- $brokerService := printf "kafka-broker-%d" $i }}


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if $root.Values.global.haproxyPrivate }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    {{- end }}
    {{- if $root.Values.external.dns.useInternal }}
    dns.alpha.kubernetes.io/internal: "{{ $distinctPrefix }}-{{ include "kafka.external.domain" $root }}"
    {{- end }}
    {{- if $root.Values.external.dns.useExternal }}
    external-dns.alpha.kubernetes.io/hostname: "{{ $distinctPrefix }}-{{ include "kafka.external.domain" $root }}"
    {{- end }}
    {{- if $root.Values.external.annotations }}
  {{ toYaml $root.Values.external.annotations | indent 4 }}
    {{- end }}
  name: {{ $fullName }}-external-{{ $i }}
  labels:
    app: kafka-broker-lb
    dnsprefix: {{  $root.Values.global.dnsPrefix }}
    pod: {{ $responsiblePod | quote }}
    chart: {{ $kafkaChart }}
    release: {{ $root.Release.Name }}
    component: controller
    frameworkId: {{ $frameworkId }}
    brokerService: {{$brokerService}}

spec:
  type: {{ $root.Values.external.type }}
  ports:
    - name: external-broker
      port: {{ $servicePort }}
      targetPort: {{ $servicePort }}
      protocol: TCP
  selector:
    app: {{ $kafkaName }}
    release: {{ $root.Release.Name }}
    dnsprefix: {{ $root.Values.global.dnsPrefix }}
    statefulset.kubernetes.io/pod-name: {{ $responsiblePod | quote }}
  {{- end }}
{{- end }}