apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.bindingtype }}
metadata:
  name: {{ .Release.Namespace }}-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ .Values.reftype }}
  name: splicedb-operator
  apiGroup: rbac.authorization.k8s.io
