{{- $fullName := include "zookeeper-fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-headless
  labels:
    app: {{ template "zookeeper.name" . }}
    chart: {{ template "splice.subchart" . }}
    release: {{ .Release.Name }}
    frameworkId: {{ include "frameworkId" . }}
spec:
  ports:
  - port: {{ .Values.global.zookeeper.configuration.clientPort }}
    name: client
  - port: {{ .Values.global.zookeeper.configuration.serverPort }}
    name: server
  - port: {{ .Values.global.zookeeper.configuration.leaderElectionPort }}
    name: leader-election
  clusterIP: None
  selector:
    app: {{ template "zookeeper.name" . }}
    release: {{ .Release.Name }}
