apiVersion: v1
description: The Apache Hbase software library is a framework that allows for the
  distributed processing of large data sets across clusters of computers using simple
  programming models.
home: https://hadoop.apache.org/
icon: http://hadoop.apache.org/images/hadoop-logo.jpg
maintainers:
- email: disla@google.com
  name: danisla
name: hbase
sources:
- https://github.com/apache/hadoop
version: 0.0.1
