#
# The list the dependent modules for this chart.  Each dependency can have any of the following fileds
#
# - name
# - version
# - condition  (comman delimited list of conditions)
# - tags
# - enabled
# - import-values
# - alias

dependencies:
  - name: zookeeper
    version: "0.0.1"
    repository: file://../zookeeper
    condition: condition.zookeeper.enabled

  - name: hadoop
    version: "0.0.1"
    repository: "file://../hadoop"
    condition: condition.hdfs.enabled

  - name: hbase
    version: "0.0.1"
    repository: "file://../hbase"
    condition: condition.hbase.enabled

  - name: jvmprofiler
    version: "0.0.1"
    repository: "file://../jvmprofiler"
    condition: condition.jvmprofiler.enabled

  - name: mlmanager
    version: "0.0.1"
    repository: "file://../mlmanager"
    condition: condition.mlmanager.enabled

  - name: jupyterhub
    version: "0.8.2"
    repository: "file://../jupyterhub"
    condition: condition.jupyterhub.enabled

  - name: rbac
    version: "0.0.1"
    repository: "file://../rbac"
    condition: condition.rbac.enabled

  - name: kafka
    version: "0.0.1"
    repository: "file://../kafka"
    condition: condition.kafka.enabled

  - name: haproxy-controller
    version: "0.0.1"
    repository: "file://../haproxy-controller"
    condition: condition.haproxy.enabled

  - name: nginx-ingress
    version: "1.23.0-splice.9"
    repository: "file://../nginx-ingress"
    condition: condition.nginx-ingress.enabled

  - name: tls-secret
    version: "0.0.1"
    repository: "file://../tls-secret"
    condition: global.tls-secret.enabled

  - name: rbac-operator
    version: "0.0.1"
    repository: "file://../rbac-operator"
    condition: condition.rbac.enabled
