apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    app: haproxy-ingress
    component: controller
    release: {{ .Release.Name }}
  name: {{ template "kubernetes-ingress.defaultTLSSecret.fullname" . }}
data:
{{ ( include "kubernetes-ingress.gen-certs" . ) | indent 2 }}
