{{- if .Values.master.service.externaIPEnabled -}}
# A service for the hbase master user interface
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hbase.hmaster.fullname" . }}-public
  labels:
    app: {{ template "hbase.name" . }}
    chart: {{ template "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: {{ include "hbase.hmaster.component" . }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
spec:
  type: LoadBalancer
  ports:
  - port: 16010
    name: masterinfo
  - port: 4002
    name: jvm-profiler
  selector:
    app: {{ template "hbase.name" . }}
    release: {{ .Release.Name }}
    component: {{ include "hbase.hmaster.component" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
  sessionAffinity: ClientIP
{{- end }}
