apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  name: {{ .Release.Name -}}-olap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name -}}-olap
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name -}}-olap
