{{- if .Values.controller.customTemplate.configMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.controller.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nginx-ingress.controller.template.configmap" . }}
data:
  nginx.tmpl: |
{{ .Files.Get "nginx.tmpl" | indent 4 }}
{{ end }}