apiVersion: v1
appVersion: "3.0"
description: Splice Machine data platform is a scale-out SQL RDBMS, data warehouse
  and machine learning management solution in one.
home: https://www.splicemachine.com
icon: https://splicemachine.github.io/sm.logo.800x200px_180509.svg
keywords:
- Database
- SQL
- Scale out
- Notebook
- ACID
maintainers:
- email: cloud-support@splicemachine.com
  name: cloud-support
name: splice-helm
version: 0.1.7
