hadoop:
  dataNode:
    persistence:
      storageClassName: "splicedb-premium"
hbase:
  master:
    persistence:
      storageClassName: "splice-file-storage"
  region:
    persistence:
      storageClassName: "splice-file-storage"
  olap:
    persistence:
      storageClassName: "splice-file-storage"
kafka:
  persistence:
    storageClassName: "splicedb-premium"
