{{- if .Values.mlflow.ingress.enabled -}}
{{- $fullName := include "mlflow.fullname" . -}}
{{- $hostName := include "mlmanager.mlflow.ingress.hosts.0" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mlflow-ingress
  {{- if .Values.mlflow.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.mlflow.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.mlflow.ingress.hosts }}
    - host: {{ $hostName | quote }}
      http:
        paths:
          - path: /mlflow/?(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.mlflow.port.mlflow }}
    {{- end }}
  {{ if .Values.global.tls.enabled }}
  {{- if .Values.mlflow.ingress.tls }}
  tls:
    {{- include "mlmanager.mlflow.ingress.tls.0" . | nindent 4 }}
  {{- end }}
  {{ end }}
{{- end }}