{{- $fullName := include "mlflow.fullname" . -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "splice.subchart" . }}
    release: {{ .Release.Name }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
spec:
  selector:
    matchLabels:
      app: {{ include "mlflow.name" . }}
      release: {{ .Release.Name }}
      dnsprefix: {{ .Values.global.dnsPrefix }}
  maxUnavailable: 1

