apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hbase.config.name" . }}
  labels:
    app: {{ template "hbase.fullname" . }}
    chart: {{ template "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: {{ include "hbase.hmaster.component" . }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
data:
  hbase-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <!--
    /*
    *
    * Licensed to the Apache Software Foundation (ASF) under one
    * or more contributor license agreements.  See the NOTICE file
    * distributed with this work for additional information
    * regarding copyright ownership.  The ASF licenses this file
    * to you under the Apache License, Version 2.0 (the
    * "License"); you may not use this file except in compliance
    * with the License.  You may obtain a copy of the License at
    *
    *     http://www.apache.org/licenses/LICENSE-2.0
    *
    * Unless required by applicable law or agreed to in writing, software
    * distributed under the License is distributed on an "AS IS" BASIS,
    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    * See the License for the specific language governing permissions and
    * limitations under the License.
    */
    -->
    <configuration>
{{- range $property := .Values.configmap.hbase.hbasesitexml }}
      <property>
{{- if regexFind "{{" $property.name }}
        <name>{{ tpl $property.name $ }}</name>
{{- else }}
        <name>{{ $property.name }}</name>
{{- end }}
{{- if regexFind "{{" $property.value }}
        <value>{{ tpl $property.value $ }}</value>
{{- else }}
        <value>{{ $property.value }}</value>
{{- end }}
{{- if $property.final }}
        <final>{{ $property.final }}</final>
{{- end }}
      </property>
{{- end }}
{{- range $i, $value := .Values.global.aws.buckets }}
      <property>
        <name>fs.s3a.bucket.{{ $value.name }}.access.key</name>
        <value>{{ $value.key }}</value>
      </property>
      <property>
        <name>fs.s3a.bucket.{{ $value.name }}.secret.key</name>
        <value>{{ $value.secret }}</value>
      </property>
{{- end }}
    </configuration>

  hbase-env.sh: |
{{- with .Values.configmap.hbase.hbaseenvsh }}
{{ tpl . $ | indent 4 }}
{{- end }}

  fairscheduler.xml: |
{{- with .Values.configmap.hbase.fairschedulerxml }}
{{ tpl . $ | indent 4 }}
{{- end }}

  log4j.properties: |
{{- with .Values.configmap.hbase.log4jproperties }}
{{ tpl . $ | indent 4 }}
{{- end }}

  shiro.ini: |
{{ with .Values.configmap.hbase.shiroini }}
{{ tpl . $ | indent 4 }}
{{ end }}
