# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hbase.olap.fullname" . }}
  labels:
    app: {{ template "hbase.name" . }}
    chart: {{ template "hbase.chart" . }}
    release: {{ .Release.Name }}
    component: {{ include "hbase.olap.component" . }}
    frameworkId: {{ include "frameworkId" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
spec:
  ports:
  - port: 16040
    name: olap
  clusterIP: None
  selector:
    app: {{ template "hbase.name" . }}
    release: {{ .Release.Name }}
    component: {{ include "hbase.olap.component" . }}
    dnsprefix: {{ .Values.global.dnsPrefix }}
